// Gridster constants
export const GridsterConstants =  {
  UPDATE_ITEM: 'UPDATE_ITEM',
  UPDATE_ROW: 'UPDATE_ROW',
  UPDATE_COL: 'UPDATE_COL',
  UPDATE_GRID: 'UPDATE_GRID',
  GENERATE_GRID: 'GENERATE_GRID',
  GENERATE_CLICK: 'GENERATE_CLICK',
  MOUSE_ENTER: 'MOUSE_ENTER',
  MOUSE_EXIT: 'MOUSE_EXIT',
  MOUSE_DOWN: 'MOUSE_DOWN',
  GENERATE_START: 'GENERATE_START',
  GENERATE_END: 'GENERATE_END'
};

